#ifndef ADC_CONF_H_
#define ADC_CONF_H_

/* Reference volt selection: ADC_VCC, ADC_INTERNAL_VREF, ADC_VREF_OFF */
#define ADC_VREF			ADC_VCC

/* Result Adjust options: ADC_RIGHT, ADC_LEFT */
#define ADC_RESULT_ADJUST	ADC_RIGHT

/* Optios: ADC_TRIGGER_ENABLE, ADC_TRIGGER_DISABLE*/
#define ADC_AUTOTRIGGER		ADC_TRIGGER_ENABLE

/* options: 
		ADC_PRESCALAR_128, ADC_PRESCALAR_64,
		ADC_PRESCALAR_32,  ADC_PRESCALAR_16,
		ADC_PRESCALAR_8,   ADC_PRESCALAR_4,
		ADC_PRESCALAR_2
*/
#define ADC_PRESCALAR ADC_PRESCALAR_128

#endif /* ADC_CONF_H_ */
